version: 2

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/Azure.Developer.ArtifactSigning.NotationPlugin" #Azure.Developer.ArtifactSigning.NotationPlugin.csproj
      - "/Azure.Developer.ArtifactSigning.NotationPlugin.UnitTests" #Azure.Developer.ArtifactSigning.NotationPlugin.UnitTests.csproj
    schedule:
      interval: "weekly"
